# R for travis documentation: https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: bioc-devel

# Strict checks
warnings_are_errors: false

branches:
  only:
    - master

# Run binary install of testthat
r_binary_packages:
  - testthat

r_packages:
  - rmarkdown
  - knitr
  - XML
  - stringr
  - data.table
  - methods
  - plyr
  - survival
  - readr

bioc_packages:
  - BiocGenerics
  - Biobase
  - GenomicRanges
  - GenomeInfoDb
  - IRanges
  - limma
  - RaggedExperiment
  - RCircos
  - S4Vectors
  - SummarizedExperiment
  - BiocStyle
  - Homo.sapiens

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  slack:
    secure: QFhqqtyfaI1CWYgiA3wQtnoUwQhPWUmBA+EK0Hx5RyEygnb3Ea/Nkl/TdWQ3BN1PTzcCEXt3dc7wTz9EVaMo5eJ4j62PIkQnh9o0efU9RW/ygj4MmLGqyiTizLGxkrj4by3PxRCxHji5idS8+8paztaBwKvK9C7XNfVAc/fFfC/9nVhlcbpTvDCBL3ThEwGdmoSJ3oV2KbP8b3oeUZHyQun0Fu7G8QKZhGSwkmo0QCG46RXeDfOK2GP28sDkjEO/PiCHoln+8HejHiwQra+J5o0kXzpdtck4sl//dmF+SAV1bCNKMCEXNJK4FZnTfQTU2rYCQrcLtDYdeWBKWnAUerqVL1VvymIh/FrYdQETsWALklJg9tg0+GPyt6YY0inhXRAcQnhAHLBGdBbXSNSxEuupx7cCge6xaGxr8iL9y6y94Nvtu56IewKLgNvdou3j6cxeXtBWIF2fMKD4JSOPCQtMLX0c/zA4PjE7WWrTeCrZEJWGzrnX/GYg+4b7Xt7aXcl8p3KN7N0tsYbX/0+GKvXNNhGegbHZex3PzvBhFO/SsV1e5D4BLggHSmP11LBBPrVKd4H49ft0Kjji//PywnNCrd3dSlFrQiHYnuYgpxo1W3XLE2tmHYGs2s/BoaR2eh2lzadchrN4xyX87okiqXhbdgdLRsYAMMOXfmygxIM=
